name: Hardhat CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master and tags branch
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_and_build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install volta
        uses: volta-cli/action@v4
        with:
          node-version: 18.x

      - name: npm ci
        run: npm ci --no-audit

      - name: npm lint
        run: npm run lint --if-present

      - name: slither
        uses: crytic/slither-action@v0.3.0

      - name: npm test
        run: npm test

      - name: npm build
        run: npm run build --if-present
        env:
          CI: true
